### ISSUE TITLE
Provide documentation on system architecture, example usages

### ISSUE THREAD

**Issue by bobbrady** [ChemAxon/jchem-microservices-examples#1]
There is no documentation describing what microservices are provided or how they interact.  A simple description with a diagram should be provided.

There is no documentation describing basic use cases and how to run them against the system.  This doesn't need to be 100% comprehensive, but it must include a few simple cases.  Simple documentation to run the use cases through REST clients must be provided.

**Comment by bzaicsek-cxn** [comment]
Please find our official documentation page: https://docs.chemaxon.com/display/docs/JChem+Microservices

or use the included live demo and documentation in the application or in its demo page: https://jchem-microservices.chemaxon.com/index.html
