### ISSUE TITLE
JMS gradlew transferData failed

### ISSUE THREAD

**Issue by ben-luck** [ChemAxon/jchem-microservices-examples#3]
I tried to follow the instructions to migrate the export mrv file using the "gradlew transferData" but failed. What is the cause here? Thanks!

C:\Users\Ben\Downloads\jchem-microservices-examples-master\migration>gradlew transferData
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.chemaxon.noam:model:1.0.0-beta555.
     Searched in the following locations:
       - https://hub.chemaxon.com/artifactory/libs-release/com/chemaxon/noam/mod
el/1.0.0-beta555/model-1.0.0-beta555.pom
       - https://hub.chemaxon.com/artifactory/libs-release/com/chemaxon/noam/mod
el/1.0.0-beta555/model-1.0.0-beta555.jar
     Required by:
         project : > com.chemaxon:io-all:22.1.0 > com.chemaxon:io-cxon:22.1.0 >
com.chemaxon:noam-connector:22.1.0
   > Could not find com.chemaxon.noam:exporter:1.0.0-beta871.
     Searched in the following locations:
       - https://hub.chemaxon.com/artifactory/libs-release/com/chemaxon/noam/exp
orter/1.0.0-beta871/exporter-1.0.0-beta871.pom
       - https://hub.chemaxon.com/artifactory/libs-release/com/chemaxon/noam/exp
orter/1.0.0-beta871/exporter-1.0.0-beta871.jar
     Required by:
         project : > com.chemaxon:io-all:22.1.0 > com.chemaxon:io-cxon:22.1.0 >
com.chemaxon:noam-connector:22.1.0
   > Could not find com.chemaxon.noam:importer:1.0.0-beta871.
     Searched in the following locations:
       - https://hub.chemaxon.com/artifactory/libs-release/com/chemaxon/noam/imp
orter/1.0.0-beta871/importer-1.0.0-beta871.pom
       - https://hub.chemaxon.com/artifactory/libs-release/com/chemaxon/noam/imp
orter/1.0.0-beta871/importer-1.0.0-beta871.jar
     Required by:
         project : > com.chemaxon:io-all:22.1.0 > com.chemaxon:io-cxon:22.1.0 >
com.chemaxon:noam-connector:22.1.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
1 actionable task: 1 executed

**Comment by aszabo19-cxn** [comment]
Thank you for the report, Ben. Missing dependencies were uploaded to hub, it should work now.
