### ISSUE TITLE
starting docker error

### ISSUE THREAD

**Issue by JustinDrugBank** [ChemAxon/jchem-microservices-examples#5]
unable to start the docker  example

➜  official-docker-images git:(master) docker compose up                                 
[+] Running 0/11
 ⠿ jms-io Error                                                                                                       0.8s
 ⠿ jms-gateway Error                                                                                                  0.8s
 ⠿ jms-calculations Error                                                                                             0.8s
 ⠿ jms-structure Error                                                                                                0.8s
 ⠿ license-server Error                                                                                               0.8s
 ⠿ jms-structurechecker Error                                                                                         0.8s
 ⠿ jms-db Error                                                                                                       0.8s
 ⠿ jms-discovery Error                                                                                                0.8s
 ⠿ jms-markush Error                                                                                                  0.8s
 ⠿ jms-config Error                                                                                                   0.8s
 ⠿ jms-reactor Error                                                                                                  0.8s
Error response from daemon: Head "https://hub.chemaxon.com/v2/cxn-docker-release/chemaxon/jms-structure/manifests/20.14.0": unknown: Authentication is required

**Comment by bzaicsek-cxn** [comment]
As the error states: you have to log in to our repository to reach our docker images. Please do not forget to also obtain a license,

**Comment by JustinDrugBank** [comment]
Hi @bzaicsek-cxn , How do I get a login? I have a license

**Comment by bzaicsek-cxn** [comment]
Hi!
You have to register (https://account.chemaxon.com/register) on our site, then you can log in and visit this site: https://download.chemaxon.com/jchem-engines
click on the "CLI with docker" button, to see your credentials you have to use.
If you, or your company is already associated with Chemaxon, then for the license file please contact your Procurement Manager for your license file. You can reach our sales team on sales@chemaxon.com .
Our official support site where all support specialist, sales person and developer is available is here: https://chemaxon.freshdesk.com/support/home
If you only want to test our application, you can ask for a 30 days evaluation license.
If you are coming from academia, and would like to enroll in our free academia program, you can get detailed information from on our sales e-mail address and on our support site also.

**Comment by JustinDrugBank** [comment]
I have a account for chemaxon and a licence file. 
How do I authenticate when I'm starting the example docker image? I get the error at the top.

**Comment by tvarga81-cxn** [comment]
Have you tried the previous advice? There are more detailed descriptions here:
https://docs.chemaxon.com/display/docs/public-repository.md#src-1806243-publicrepository-docker
If you have specific problems with the setup, you can also get advice on the official support site on the link above.

**Comment by JustinDrugBank** [comment]
@tvarga81 @bzaicsek-cxn Thanks for your help! I have it up and running
